# Use root/example as user/password credentials

services:
    db:
        image: mariadb
        restart: always
        ports:
            - 3306:3306
        environment:
            MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MARIADB_USER: ${DB_USER}
            MARIADB_PASSWORD: ${DB_PASSWORD}
        healthcheck:
            test:
                [
                    "CMD",
                    "mariadb-admin",
                    "ping",
                    "-h",
                    "localhost",
                    "-u",
                    "root",
                    "-p$$MARIADB_ROOT_PASSWORD",
                ]
            interval: 10s
            timeout: 5s
            retries: 5
    cache:
        image: redis:7.4.5-alpine
        restart: always
        ports:
            - "6379:6379"
        command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
        volumes:
            - cache:/data
volumes:
    cache:
        driver: local
    # adminer:
    #     image: adminer
    #     restart: always
    #     ports:
    #         - 8080:8080
