# Use root/example as user/password credentials

services:
    db:
        image: mariadb:10.6-ubi
        restart: always
        volumes:
            - mariadb_data:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MARIADB_DATABASE: ${DB_NAME}
        healthcheck:
            test:
                [
                    "CMD",
                    "mariadb-admin",
                    "ping",
                    "-h",
                    "localhost",
                    "-u",
                    "root",
                    "-p$$MARIADB_ROOT_PASSWORD",
                ]
            interval: 10s
            timeout: 5s
            retries: 5
    redis:
        image: redis:7.4.5-alpine
        restart: always
        ports:
            - "6379:6379"
        command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
        volumes:
            - redis:/data
volumes:
    redis:
        driver: local
    mariadb_data:
